const {chromium}=require('C:/Users/david/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const path=require('path');
const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'msedge'});
 try{
  const page=await browser.newPage({viewport:{width:1600,height:1000}});const errors=[];
  page.on('pageerror',e=>{errors.push(e.message);console.error('pageerror:',e.message);});
  await page.goto('file:///'+path.resolve(__dirname,'../index.html').replace(/\\/g,'/'));
  await page.waitForFunction(()=>typeof people!=='undefined'&&people.length===8&&financeBots.length===3);
  // Deterministic motion tests use elapsed seconds, without waiting for real-time walks.
  console.log(await page.evaluate(()=>{
   const check=(ok,label)=>{if(!ok)throw Error(label);};
   const advance=(seconds,dt=1/60)=>{for(let t=0;t<seconds;t+=dt)people.forEach(p=>p.update(dt));};
   const seatsValid=()=>{
    check(people.every(p=>p.state==='seated'||p.state==='playing'),`Not settled at a seat: ${people.map(p=>p.cfg.id+':'+p.state).join(',')}`);
    check(new Set(people.map(p=>p.seat.id)).size===8,'Duplicate seat assignment');
    for(const p of people){
     check(p.group.position.distanceTo(p.seat.position)<.001,'Seat alignment');
     check(Math.abs(Math.atan2(Math.sin(p.group.rotation.y-p.seat.yaw),Math.cos(p.group.rotation.y-p.seat.yaw)))<.05,'Seat facing');
     p.group.updateMatrixWorld(true);
     check(p.floor===1&&p.home?.floor===1&&!p.upperHome,'Human team must remain on the ground floor');
     check(p.legs.every(leg=>leg.root.visible)&&p.headRoot.visible,'Ground-floor team should be represented as humans');
     check(p.torso.geometry.type==='ExtrudeGeometry','Human characters should keep their original clothing/body model');
     check(p.speechSprite?.parent===p.group,'Character speech bubble must follow its owner');
     check(p.speechSprite.position.y>p.rig.position.y+p.headRoot.position.y+.39*1.1+p.speechSprite.scale.y/2,'Character speech bubble must float above the head without overlap');
    }
   };
   setGlobalOrder('work');
   check(people.every(p=>p.speech.sprite.visible&&p.speech.status==='typing'),'Every character should start a floating typed dialogue on team activity');
   globalOrder='chill';advance(12);seatsValid();
   check(people.every(p=>p.seat===p.home),'Work seats');
   globalOrder='rest_all';advance(.3);check(people.every(p=>p.state==='standing-up'),'Stand before walk');
   advance(100);seatsValid();
   check(people.filter(p=>p.seat===p.rest).length===6&&people.filter(p=>p.seat?.kind==='pingpong').length===2,'Rest should assign two agents to ping-pong and the rest to lounge seats');
   globalOrder='rest_half';advance(100,1/30);seatsValid();check(people.filter(p=>p.seat===p.rest).length===4,'Half rest');
   globalOrder='chill';advance(100,1/120);seatsValid();
   check(scene.getObjectByName('desk-plan-paper')&&scene.getObjectByName('desk-pencil'),'Missing desk plan and pencil');
   const analyst=people.find(p=>p.cfg.id==='analyst'),oldTab=analyst.activeScreenTab;
   setAgentSpeech('analyst','Reviso la señal antes de enviarla.',{typing:true,duration:2});
   check(analyst.speech.status==='typing'&&analyst.speech.displayText==='...','Speech bubble must show typing dots first');
   advance(.8);check(analyst.speech.status==='message'&&analyst.speech.displayText.includes('Reviso la señal'),'Speech bubble must reveal the message after typing');
   globalOrder='work';analyst.tabSwitchTimer=.001;analyst.update(.01);
   check(analyst.activeScreenTab===(oldTab+1)%3,'Desk screen tab did not change');
   check(officeDeskScreenMeshes.length===6,'The bot floor must not contain computer workstations');
   check(new Set(tradingScreenMeshes.map(screen=>screen.texture)).size===3,'Wall screens share textures');
   check(new Set(officeDeskScreenMeshes.map(screen=>screen.texture)).size===officeDeskScreenMeshes.length,'Desk screens share textures');
   check(officeDeskScreenMeshes.every(desk=>!tradingScreenMeshes.some(wall=>wall.texture===desk.texture)),'Desk screen shares a wall texture');
   analyst.activeScreenTab=0;lastOfficeScreenUpdate=-Infinity;updateTradingScreens();
   const wallTabFrames=tradingScreenMeshes.map(screen=>Array.from(screen.ctx.getImageData(0,0,500,60).data).join(','));
   analyst.activeScreenTab=1;lastOfficeScreenUpdate=-Infinity;updateTradingScreens();
   check(tradingScreenMeshes.every((screen,index)=>Array.from(screen.ctx.getImageData(0,0,500,60).data).join(',')===wallTabFrames[index]),'Desk tab change altered a wall screen');
   const analystScreens=officeDeskScreenMeshes.filter(screen=>screen.agentIndex===analyst.index);
   check(analystScreens.length===2&&analystScreens.every(screen=>screen.canvas.toDataURL()===tradingScreenMeshes[1].canvas.toDataURL()),'Human desk monitors do not reflect the agent tab');
   advance(120);seatsValid();
   check(financeBots.every(bot=>bot.group.position.y>=8&&bot.group.name.startsWith('finance-bot-')&&bot.group.children.some(part=>part.geometry?.type==='SphereGeometry')),'The upper floor should have its own floating spherical bot team');
   check(financeBots.every(bot=>bot.visor.parent===bot.core&&Math.abs(bot.visor.position.y)<.1),'Bot visors should be attached to the spherical shells');
   check(financeBots.every(bot=>!people.some(person=>person.group===bot.group)),'Human characters and bots must be separate entities');
   check(!scene.getObjectByName('finance-elevator-platform')&&typeof moveTeamToFloor==='undefined'&&typeof moveSelectedAgentToFloor==='undefined','Floor changes must not provide a way to move either team');
   const financeDeck=scene.getObjectByName('upper-floor-blue-deck');
   financeDeck.geometry.computeBoundingBox();
   const deckSize=financeDeck.geometry.boundingBox.getSize(new THREE.Vector3());
   check(deckSize.x<28&&deckSize.z<24,'Bot room should be compact around its finance equipment');
   const tableBills=officeLevelGroups[2].children.filter(object=>object.name.startsWith('cash-table-dollar-'));
   check(tableBills.length>=12&&tableBills.every(bill=>bill.material.map?.image.width===512),'Visible dollar bills should be spread across the finance table');
   setOfficeFloorView(2);check(officeLevelGroups[2].visible&&!officeLevelGroups[1].visible,'Second-floor view should show the blue finance floor only');
   check(financeBots.every(bot=>bot.group.visible)&&people.every(person=>!person.group.visible),'Changing floor view must hide the other team without moving it');
   const robotStart=financeBots[0].group.position.clone();
   updateFinanceFloor(.2);
   check(financeBots[0].group.position.distanceTo(robotStart)>.05,'Bots should keep moving while they patrol the finance floor');
   const countedBefore=financeVault.counted;
   recordMoneyMovement(25,true);
   const winFlow=financeMoneyFlows[0],winBot=winFlow.bot;
   for(let i=0;i<900&&!winFlow.carrying;i++)updateFinanceFloor(1/30);
   check(winFlow.carrying&&winFlow.bundle.parent===winBot.carrier,'A winning trade bundle must be carried by a bot');
   const carryingPosition=winBot.group.position.clone();updateFinanceFloor(.3);
   check(winBot.group.position.distanceTo(carryingPosition)>.1&&winFlow.bundle.parent===winBot.carrier,'The bot must move while carrying winning-trade money');
   for(let i=0;i<900&&(financeMoneyFlows.length||financePendingDeliveries.length);i++)updateFinanceFloor(1/30);
   check(financeVault.counted===countedBefore+25&&financeDeposits.length===1&&financeDeposits[0].position.z<9,'Winning trade money must be delivered to the vault');
   const discardedBefore=financeVault.discarded;
   recordMoneyMovement(15,false);
   const lossFlow=financeMoneyFlows[0];
   for(let i=0;i<900&&(financeMoneyFlows.length||financePendingDeliveries.length);i++)updateFinanceFloor(1/30);
   check(financeVault.discarded===discardedBefore+15&&financeTrash.length===1&&financeTrash[0].position.z>10,'Losing trade money must be delivered to the trash');
   setOfficeFloorView(1);check(people.every(person=>person.group.visible)&&financeBots.every(bot=>!bot.group.visible),'Returning to the human floor must restore only the human team');
   globalOrder='rest_all';advance(100);updateOfficeLeisure(.1);
   check(people.filter(p=>p.seat?.kind==='pingpong'&&p.state==='playing').length===2,'Ping-pong needs two actual players at the table');
   check(officeLeisure.table&&officeLeisure.ball.visible&&officeLeisure.paddles.length===2&&officeLeisure.paddles.every(p=>p.visible),'Ping-pong break animation is not active with players present');
   const activeBallPosition=officeLeisure.ball.position.clone(),activePaddleRotation=officeLeisure.paddles[0].rotation.y;
   updateOfficeLeisure(.2);check(officeLeisure.ball.position.distanceTo(activeBallPosition)>.01&&officeLeisure.paddles[0].rotation.y!==activePaddleRotation,'Ping-pong should animate during an actual game');
   globalOrder='work';advance(100);const idleBallPosition=officeLeisure.ball.position.clone(),idlePaddleRotation=officeLeisure.paddles[0].rotation.y;
   updateOfficeLeisure(.2);
   check(!officeLeisure.ball.visible&&officeLeisure.ball.position.distanceTo(idleBallPosition)<.001&&officeLeisure.paddles[0].rotation.y===idlePaddleRotation,'Ping-pong equipment must stay still when nobody is playing');
   globalOrder='rest_all';advance(100);
   const restingAgent=people[0],elbowBefore=restingAgent.arms[1].elbow.rotation.x;
   let eatingAnimationMoved=false;
   for(let i=0;i<15;i++){advance(.1);if(Math.abs(restingAgent.arms[1].elbow.rotation.x-elbowBefore)>.01)eatingAnimationMoved=true;}
   check(eatingAnimationMoved,'Break-time eating animation did not move');
   setCameraView('overview');
   return 'Eight human seats, continuous separate bot patrol, bot-carried win/loss deliveries, human desk screens, lounge and ping-pong animations passed';
  }));
  await page.waitForTimeout(300);
  await page.screenshot({path:path.resolve(__dirname,'office-overview.png')});
  await page.evaluate(()=>setOfficeFloorView(2));
  await page.waitForTimeout(300);
  await page.screenshot({path:path.resolve(__dirname,'office-bots.png')});
  await page.evaluate(()=>setCameraView('analyst'));
  await page.waitForTimeout(300);await page.screenshot({path:path.resolve(__dirname,'office-seated.png')});
  console.log(JSON.stringify({errors}));assert.deepEqual(errors,[]);
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
